# my-laravel-app/docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_php
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    # --- START OF MODIFICATION ---
    command: bash -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache; \
                      chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache; \
                      [ -f /var/www/html/database/database.sqlite ] && chmod 664 /var/www/html/database/database.sqlite || true; \
                      chown -R www-data:www-data /var/www/html/storage/framework/sessions; \
                      chmod -R 775 /var/www/html/storage/framework/sessions; \
                      php-fpm"
    # --- END OF MODIFICATION ---

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app