# my-laravel-app/docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_php
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    # --- START OF MODIFICATION ---
    command: bash -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache; \
                      chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache; \
                      [ -f /var/www/html/database/database.sqlite ] && chmod 664 /var/www/html/database/database.sqlite || true; \
                      chown -R www-data:www-data /var/www/html/storage/framework/sessions; \
                      chmod -R 775 /var/www/html/storage/framework/sessions; \
                      php-fpm"
    # --- END OF MODIFICATION ---

  nginx:
      # --- MUDANÇA MAIS IMPORTANTE AQUI ---
      build: # Diga ao Docker Compose para CONSTRUIR a imagem Nginx
        context: ./docker # O contexto para o build é a pasta 'docker'
        dockerfile: nginx.Dockerfile # Use o Dockerfile recém-criado para o Nginx
      # --- FIM DA MUDANÇA MAIS IMPORTANTE ---
      container_name: laravel_nginx
      restart: unless-stopped
      ports:
        - "8010:80"
      volumes:
        # Você pode manter este volume, pois é o volume da aplicação em si, não da configuração Nginx
        - .:/var/www/html
        # REMOVA OU COMENTE A LINHA ABAIXO, ELA CAUSA O PROBLEMA:
        # - ./docker/nginx.conf:/etc/nginx/conf.d/app.conf
      depends_on:
        - app